## possible value: production , development

global:
  mode: development
  secret: "feaz$as"
server:
  port:  8091

client:
  type: "gost"
  server: http://192.168.10.152:8091
  localPort: 10922
  name: suzou1